package com.maxoreau.springboot.bataillenavale.controllers;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.maxoreau.springboot.bataillenavale.models.Game;
import com.maxoreau.springboot.bataillenavale.models.Player;
import com.maxoreau.springboot.bataillenavale.repositories.GameRepository;
import com.maxoreau.springboot.bataillenavale.repositories.PlayerRepository;


@RestController				
@RequestMapping("/battleship")	// This means URL's start with /battleship (after Application path)
public class GameController {
	
						// This means to get the bean called userRepository
	@Autowired			// Which is auto-generated by Spring, we will use it to handle the data
	private GameRepository gameRepo;
	
	@Autowired
	private PlayerRepository playerRepo;
    
	
    @PostMapping // Map ONLY POST Requests
	public void createPlayer (@RequestBody Player player) {
    	System.out.println("Rest createPlayer() entered");
    	System.out.println(player);
    	playerRepo.save(player);
	}

	@GetMapping("/players")
	public List<Player> getAllPlayers() {
		// This returns a JSON or XML with the users
    	System.out.println("Rest getAllPlayers() entered");
		return (List<Player>) playerRepo.findAll();
	}

	@GetMapping("/games")
	public List<Game> getAllgames() {
		// This returns a JSON or XML with the users
    	System.out.println("Rest getAllPlayers() entered");
		return (List<Game>) gameRepo.findAll();
	}

}
